export interface FetcResponseCasePersons {
    data: Person[];
    recordsCount: number;
}

export interface Person {
    id: number;
    documentNumber: string;
    documentTypeId: number;
    fullName: string;
    birthDate: string;
    gender: string;
    inactive: boolean;
    documentType: DocumentType;
    caseFamilyGroupsParent: CaseFamilyGroupsParent[];
}

export interface DocumentType {
    id: number;
    documentType: string;
    casePersons: any[];
}

export interface CaseFamilyGroupsParent {
    map: any;
    id: number;
    personId: number;
    taskId: number;
    parentId: number;
    relationshipTypeId: any;
    enrollementDate: string;
    enrollementUserId: number;
    inactive: boolean;
    parent: any;
    person: any;
    relationshipType: any;
    task: any;
    caseFamilyGroupsFilledForms: any[];
}

export interface Deleteperson {
    taskId: number,
    personId: number,
    relationshipTypeId: number | undefined | string,
    inactive: boolean,
    person?: PersonCase,
}

export interface AssignPerson {
    taskId?: number,
    personId?: number,
    relationShipTypeId?: number | undefined | string
}

export interface PersonCase {
    birthDate: Date,
    documentNumber: string,
    documentTypeId: number,
    fullName: string,
    gender: string,
    id: number,
}

export interface PersonSelect {
    taskId: number,
    personId: number,
    relationShipTypeId: number | undefined | string,
    inactive?: boolean,
}



// Generated by https://quicktype.io

export interface AssignFilledFormToCaseInterface {
    id:                 number;
    caseFamilyGroupsId: number;
    taskId:             number;
    formsInUseId:       string;
    filledFormsId:      string;
    caseFamilyGroups:   CaseFamilyGroups;
    task:               null;
}

export interface CaseFamilyGroups {
    id:                          number;
    personId:                    number;
    taskId:                      number;
    parentId:                    null;
    relationshipTypeId:          number;
    enrollementDate:             string;
    enrollementUserId:           number;
    inactive:                    boolean;
    parent:                      null;
    person:                      null;
    relationshipType:            null;
    task:                        null;
    caseFamilyGroupsFilledForms: null[];
}
