import { TaskI } from "../task/taskInterface";

export interface FetchResponseCaseFamily {
  data: CaseFamilyPersonI[];
  recordsCount: number;
}

export interface CaseFamilyPersonI {
  id: number;
  personId: number;
  taskId: number;
  parentId: number;
  relationshipTypeId: number | null;
  enrollementDate: string;
  enrollementUserId: number;
  inactive: boolean;
  person: {
    id: number;
    documentNumber: string;
    documentTypeId: number;
    fullName: string;
    birthDate: string;
    gender: string;
    inactive: boolean;
  };
  relationshipType: string | null;
}

export interface DuplicateCaseInterface {
  newTaskId: number,
  caseFamilyGroupsId: number[]
}

// Generated by https://quicktype.io

export interface AssignFormToCaseFamily {
  caseFamilyGroupsId: number[];
  formsInUseId:       string;
  filledFormsId:      string;
}


// Generated by https://quicktype.io

export interface FetchResponseDuplicateCaseFamily {
  id:                          number;
  personId:                    number;
  taskId:                      number;
  parentId:                    number;
  relationshipTypeId:          number;
  enrollementDate:             string;
  enrollementUserId:           number;
  inactive:                    boolean;
  parent:                      null;
  person:                      null;
  relationshipType:            null;
  task:                        TaskI;
  caseFamilyGroupsFilledForms: any[];
}

